server:
  port: 8081
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sp3?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456@Root
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yml
  devtools:
    restart:
      enabled: true
  data:
    web:
      pageable:
        size-parameter: pageSize
        default-page-size: 20
        max-page-size: 500
      sort:
        sort-parameter: order
    redis:
      database: 6
      host: 127.0.0.1
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
      connect-timeout: 1000
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest